version: "3"

services:
  be-compose:
    image: img-be_cyber_media
    container_name: cons-be_cyber_media
    ports:
      - "3070:3069"
    # depends_on = service phụ thuộc => có nó thì service hiện tại mới chạy đc (kiểm soát thứ tự chạy)
    depends_on:
      - mysql-compose

    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ACCESS_TOKEN_EXPIRES=${ACCESS_TOKEN_EXPIRES}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - REFRESH_TOKEN_EXPIRES=${REFRESH_TOKEN_EXPIRES}

    command: ["npm", "run", "start"]

  mysql-compose:
    image: mysql
    container_name: some-mysql-compose
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3307:3306"
